# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122ULVIzLin50etoIj7qiL6x96Uhs_Z5T
"""

pip install wandb

import wandb

# Authenticate using your API key (if not already logged in)
wandb.login()

# Specify the project and entity name
project_name = "ASR East Africa"
entity_name = "asr-africa-research-team"  # Replace with your WandB entity name

# Initialize the API
api = wandb.Api()

# Get all runs from the specified project
runs = api.runs(f"{entity_name}/{project_name}")

# Iterate through the runs and delete the failed and crashed ones created by you
for run in runs:
    creator = run.config.get("wandb_username", None)  # Try to access the creator from config metadata if available

    if run.state in ['failed', 'crashed'] and creator == "kyagabajonah":  # Replace with your WandB username
        print(f"Deleting run: {run.name} (ID: {run.id}, State: {run.state})")
        run.delete()
    else:
        print(f"Skipping run: {run.name} (ID: {run.id}, State: {run.state}, Creator: {creator})")